import {
  LivewellImg,
  PathwaysImg,
  Aim100Img,
  MarsaImg,
  FruitEcommerceImg,
  MadrasaMobileImg,
  MuslimHelperImg,
  MbfQuranImg,
  OgasImg,
  EpeImg,
} from '../../assets';

export const galleryProjects = [
  {
    id: 'livewell',
    category: 'ecommerce',
    num: '01',
    nodeTag: 'ECOMMERCE_NODE // 01',
    badge: 'GLOBAL STOREFRONT',
    title: 'Livewell Brands',
    role: 'Global Multi-Brand E-Commerce Engine',
    desc: 'Architected an ultra-fast multi-tenant luxury storefront serving 14 currencies with zero-latency visual catalog filtering, localized micro-frontends, and automated high-throughput inventory arbitration.',
    img: LivewellImg,
    badgeA: 'TTFB: 42MS',
    badgeB: '+340% CONV',
    metricA: '+340% Rev',
    metricB: '42ms TTFB',
    metricC: '2.4M MAU',
    stack: ['Next.js 14', 'Shopify Headless', 'Edge CDN', 'Rust Worker Mesh', 'Redis Enterprise'],
  },
  {
    id: 'pathways',
    category: 'web-solutions',
    num: '02',
    nodeTag: 'HEALTH_MESH // 02',
    badge: 'MEDTECH CORE',
    title: 'Pathways To Prevention',
    role: 'Healthcare & Diagnostic Digital Platform',
    desc: 'Pioneering diagnostic preventive portal consolidating multi-clinic pathology telemetry, real-time biometrics charting, and patient follow-up automated triage in compliance with zero-trust regulatory frameworks.',
    img: PathwaysImg,
    badgeA: 'SECURITY: HL7_L4',
    badgeB: '650K PATIENTS',
    metricA: '99.999% SLA',
    metricB: 'HIPAA + HL7 Compliant',
    metricC: '650K+ Patients',
    stack: ['FastAPI', 'WebSockets', 'HIPAA Edge', 'React', 'PostgreSQL Encrypted', 'AWS MedTech'],
  },
  {
    id: 'aim100',
    category: 'web-solutions',
    num: '03',
    nodeTag: 'MEDIA_ENGINE // 03',
    badge: '3D SPATIAL',
    title: 'Aim Hundred C',
    role: 'Industrial & Creative Media Systems',
    desc: 'Spatial storytelling and automated digital media production hub. Bridges industrial 3D configuration with cinema-grade interactive showreels and instant WebGL interactive material previews.',
    img: Aim100Img,
    badgeA: 'RENDER: 60FPS',
    badgeB: '8K SPATIAL',
    metricA: '8K Rendering',
    metricB: '60 FPS WebGL',
    metricC: '4.9/5 Score',
    stack: ['Three.js', 'WebGL 2.0', 'GSAP', 'Node Media Server', 'Headless Content Graph'],
  },
  {
    id: 'marsa',
    category: 'ecommerce',
    num: '04',
    nodeTag: 'FULFILL_CORE // 04',
    badge: 'HYPER-COMMERCE',
    title: 'Marsa Store',
    role: 'High-Throughput Mobile & Web Commerce',
    desc: 'Ultra-reliable, high-velocity grocery and perishables logistics engine capable of real-time inventory locking, dynamic courier route routing, and fractional millisecond transaction reconciliation.',
    img: MarsaImg,
    badgeA: 'PEAK: 12K REQ/S',
    badgeB: '99.98% UPTIME',
    metricA: '1.2M Orders/Day',
    metricB: '99.98% Fulfillment',
    metricC: '350ms Checkout',
    stack: ['Golang', 'Kafka', 'Distributed DB', 'Flutter', 'CockroachDB'],
  },
  {
    id: 'fruit-ecommerce',
    category: 'ecommerce',
    num: '05',
    nodeTag: 'AGRI_TRADE // 05',
    badge: 'DIRECT COMMERCE',
    title: 'Fruit E-Commerce',
    role: 'Agri-Tech & Grocery Commerce Marketplace',
    desc: 'Fresh agricultural marketplace connecting regional farm producers directly with enterprise grocery hubs through dynamic pricing, automated load balancing, and cold-chain IoT monitors.',
    img: FruitEcommerceImg,
    badgeA: 'FLOW: $48M',
    badgeB: '85K MERCHANTS',
    metricA: '$48M Gross Flow',
    metricB: '99.9% Fresh SLA',
    metricC: '85K Merchants',
    stack: ['React', 'Node.js', 'AWS Cloud', 'PostgreSQL', 'Redis'],
  },
  {
    id: 'madrasa-mobile',
    category: 'mobile',
    num: '06',
    nodeTag: 'EDTECH_SUITE // 06',
    badge: 'EDTECH PLATFORM',
    title: 'Madrasa Mobile',
    role: 'Educational Institution Mobile Suite',
    desc: 'Comprehensive institutional education ecosystem delivering interactive lesson streaming, curriculum tracking, student grading dashboards, and offline localized sync across smartphones and tablets.',
    img: MadrasaMobileImg,
    badgeA: 'MAU: 450K+',
    badgeB: 'RATING 4.9★',
    metricA: '450K+ Learners',
    metricB: '99.95% Offline Sync',
    metricC: '4.9 App Store',
    stack: ['Flutter', 'Dart', 'Offline SQLite', 'Firebase', 'Cloud Functions'],
  },
  {
    id: 'muslim-helper',
    category: 'enterprise-ai',
    num: '07',
    nodeTag: 'AI_ASSISTANT // 07',
    badge: 'AI ASSISTANT',
    title: 'Muslim Helper',
    role: 'AI-Powered Lifestyle & Astrometry Engine',
    desc: 'Intelligent daily companion application utilizing localized GPS astronomy computation, AI semantic knowledge retrieval, real-time audio recitation parsing, and zero-battery background telemetry.',
    img: MuslimHelperImg,
    badgeA: 'DAU: 1.8M',
    badgeB: '99.99% ACC',
    metricA: '1.8M Active Daily',
    metricB: '99.99% Calculation Acc',
    metricC: '4.9/5 Rating',
    stack: ['React Native', 'Swift', 'FastAPI', 'Swift CoreLocation', 'Kotlin Daemons'],
  },
  {
    id: 'mbf-quran',
    category: 'mobile',
    num: '08',
    nodeTag: 'TYPO_CORE // 08',
    badge: 'AUDIO & TYPOGRAPHY',
    title: 'MBF Quran',
    role: 'High-Fidelity Mobile Typography & Audio Streamer',
    desc: 'State-of-the-art mobile reading and audio streaming application with vector typography rendering, multi-translation comparative analysis, and high-fidelity synchronized audio recitations.',
    img: MbfQuranImg,
    badgeA: '60 FPS VECTOR',
    badgeB: '2.1M USERS',
    metricA: '2.1M Installs',
    metricB: '60 FPS Typography',
    metricC: 'Zero Latency Audio',
    stack: ['Flutter', 'Dart', 'CoreAudio', 'WebGL Vector Engine'],
  },
  {
    id: 'ogas',
    category: 'enterprise-ai',
    num: '09',
    nodeTag: 'ENERGY_SCADA // 09',
    badge: 'INDUSTRIAL SCADA',
    title: 'OGAS Energy',
    role: 'Enterprise Industrial SCADA Telemetry & Energy Suite',
    desc: 'Enterprise energy and resource management operations dashboard. Processes high-concurrency SCADA sensor telemetry, predictive consumption analytics, and industrial automated failover protocols.',
    img: OgasImg,
    badgeA: 'SENSORS: 24K',
    badgeB: '99.999% SLA',
    metricA: '99.999% SLA',
    metricB: '24K Sensors Active',
    metricC: 'Sub-second Alarming',
    stack: ['React', 'Golang', 'InfluxDB', 'TypeScript', 'Docker', 'WebSockets'],
  },
  {
    id: 'epe',
    category: 'web-solutions',
    num: '10',
    nodeTag: 'ENTERPRISE_HUB // 10',
    badge: 'OPERATIONS HUB',
    title: 'EPE Platform',
    role: 'Enterprise Project & Engineering Operations Platform',
    desc: 'Centralized enterprise operations and equipment engineering portal. Integrates project estimation, procurement tracking, technical schematics visualization, and cross-team workflow orchestration.',
    img: EpeImg,
    badgeA: 'P95: < 100MS',
    badgeB: '99.98% SLA',
    metricA: '99.98% Uptime',
    metricB: 'Sub-100ms Query',
    metricC: 'Enterprise Tier',
    stack: ['React 18', 'GraphQL', 'PostgreSQL', 'Node.js', 'TailwindCSS'],
  },
];
